시그모이드 함수(값을 0~1 사이의 값으로 만드는 함수)를 사용해서 확률값을 만든다.

z = a*(무게) + b*(길이) + c*(대각선) + d*(높이) + e*(넓이) + f
에서 a-f는 가중치 혹은 계수고, z를 시그모이드 함수를 통해 0-1의 값으로 만든다.
z = sigmoid(z)

회귀는 결정계수
분류는 정확도

---
오늘의 결론: 수학 함수를 믿자!


In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

fish = pd.read_csv('http://bit.ly/fish_csv_data')
#print(fish) #pandas 하서 컬럼명이 존재

#print(fish['Species']) #Species 열의 값만 출력
#print(pd.unique(fish['Species'])) # 고유한 Species값들만 출력(pandas 제공)
#print(fish.head()) # 앞의 5값만 출력(pandas 제공)

fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(fish_input,fish_target, random_state=42)

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors=10)

kn.fit(train_scaled,train_target)
print("예측값:",kn.predict(test_scaled[:5]))
print("정답값:",test_target[:5])

print("타겟 순서")
print(kn.classes_)
proba = kn.predict_proba(test_scaled[:5])
print("예측 확률들")
print(np.round(proba, decimals = 1))

예측값: ['Perch' 'Smelt' 'Perch' 'Perch' 'Perch']
정답값: ['Perch' 'Smelt' 'Pike' 'Whitefish' 'Perch']
타겟 순서
['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']
예측 확률들
[[0.  0.  0.6 0.  0.4 0.  0. ]
 [0.  0.  0.1 0.  0.  0.9 0. ]
 [0.  0.  0.6 0.4 0.  0.  0. ]
 [0.  0.  0.5 0.  0.4 0.  0.1]
 [0.  0.  0.8 0.  0.2 0.  0. ]]


In [51]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

fish = pd.read_csv('http://bit.ly/fish_csv_data')
#print(fish) #pandas 하서 컬럼명이 존재

#print(fish['Species']) #Species 열의 값만 출력
#print(pd.unique(fish['Species'])) # 고유한 Species값들만 출력(pandas 제공)
#print(fish.head()) # 앞의 5값만 출력(pandas 제공)

fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(fish_input,fish_target, random_state=42)

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

bream_smelt_indexes = (train_target == 'Bream')|(train_target=='Smelt')
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]
#print(train_target)
#print(target_bream_smelt)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_bream_smelt,target_bream_smelt)
print(lr.predict(train_bream_smelt[:5]))
print(lr.classes_)
print(np.round(lr.predict_proba(train_bream_smelt[:5]), decimals=3))

print(lr.coef_,lr.intercept_) # 계수랑 절편 출력

decisions = lr.decision_function(train_bream_smelt[:5]) #맨위 글에서 z값을 출력하는 격
print(np.round(decisions,decimals = 2))

from scipy.special import expit
print(expit(decisions)) #expit은 시그모이드 함수
#즉 이건 bream의 확률을 출력하는 것

['Bream' 'Smelt' 'Bream' 'Bream' 'Bream']
['Bream' 'Smelt']
[[0.998 0.002]
 [0.027 0.973]
 [0.995 0.005]
 [0.986 0.014]
 [0.998 0.002]]
[[-0.40451732 -0.57582787 -0.66248158 -1.01329614 -0.73123131]] [-2.16172774]
[-6.03  3.57 -5.27 -4.24 -6.06]
[0.00239993 0.97262675 0.00513614 0.01414953 0.00232581]
