* 시그모이드 함수: 이진 분류에 적합
* 소프트 맥스 함수: 다중 분류에 적합. 여러 함수의 출력값의 합이 1이 되도록 조정해서 확률 나오는거다. Z1 = z1/sum(z1:z7) 이런식임.
* 활성화 함수(시그모이드, 소프트맥스)는 로지스틱 회귀에서 알아서 정해준다.

In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

fish = pd.read_csv('http://bit.ly/fish_csv_data')
#print(fish) #pandas 하서 컬럼명이 존재

#print(fish['Species']) #Species 열의 값만 출력
#print(pd.unique(fish['Species'])) # 고유한 Species값들만 출력(pandas 제공)
#print(fish.head()) # 앞의 5값만 출력(pandas 제공)

fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(fish_input,fish_target, random_state=42)

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=20,max_iter=1000) #max_iter은 학습 반복 횟수. 100이 기본값.
#C는 규제제어. 작을수록 규제가 큰 것. 20에서 줄여나가자는 것.
lr.fit(train_scaled,train_target)

print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

print(test_target[:5])
print(lr.predict(test_scaled[:5]))

print(lr.classes_)
print(np.round(lr.predict_proba(test_scaled[:5]),decimals=3))

print(lr.coef_.shape, lr.intercept_.shape) #7개의 특성이라서 총 7개의 함수가 있는거임.
#그 7개의 가중치와 절편으로 각각의 z값을 구하고, 시그모이드함수에 넣어서 0~1 사이의 값으로 변환후 값이 제일 높은걸로 예측된다.
#시그모이드로 2개의 값을 구해야하는 경우, 하나만 구하고 나머지는 1-상대확률 구하고 구하면 됨.
#그래서 시그모이드는 이진분류에 적합하고, 지금처럼 여러개일때(다중분류) 소프트맥스 함수 써야한다.
print(lr.coef_,lr.intercept_)

0.9327731092436975
0.925
['Perch' 'Smelt' 'Pike' 'Whitefish' 'Perch']
['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']
['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']
[[0.    0.014 0.842 0.    0.135 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.934 0.015 0.016 0.   ]
 [0.011 0.034 0.305 0.006 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]
(7, 5) (7,)
[[-1.50605455 -1.03747913  2.60919713  7.6942274  -1.18603342]
 [ 0.19200046 -1.99988812 -3.79617725  6.5031264  -2.00022754]
 [ 3.55793539  6.36988929 -8.52233732 -5.75397233  3.79233438]
 [-0.11453309  3.61060121  3.94464503 -3.62243904 -1.75981679]
 [-1.40843717 -6.09242191  5.28629633 -0.86696569  1.84518455]
 [-1.33419949  1.48153392  1.38217547 -5.6602348  -4.39228964]
 [ 0.61328846 -2.33223526 -0.90379939  1.70625807  3.70084846]] [-0.10345047 -0.27281217  3.24444852 -0.17565069  2.64960025 -6.7204285
  1.37829306]
